//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_T
    {
        public Admin_T()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Courses = new HashSet<Course>();
            this.ForgottenPasses = new HashSet<ForgottenPass>();
            this.LiaisonReports = new HashSet<LiaisonReport>();
            this.LiaisonReports1 = new HashSet<LiaisonReport>();
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int LastUpdateUserID { get; set; }
        public string FilePath { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string isAdmin { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<ForgottenPass> ForgottenPasses { get; set; }
        public virtual ICollection<LiaisonReport> LiaisonReports { get; set; }
        public virtual ICollection<LiaisonReport> LiaisonReports1 { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
