//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public Assignment()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ID { get; set; }
        public System.DateTime AssignmentDeadline { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public string FilePath { get; set; }
        public string MarkingCriteria { get; set; }
        public string AssignmentStructure { get; set; }
        public string Feedback { get; set; }
        public int LastUpdateUserID { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual Course Course { get; set; }
    }
}
