//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgottenPass
    {
        public ForgottenPass()
        {
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int PassID { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public System.DateTime LockOutEndDate { get; set; }
        public bool LockOutEnabled { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int AccessFailedCount { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int LastUpdateUserID { get; set; }
    
        public virtual Admin_T Admin_T { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
