//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiaisonReport
    {
        public LiaisonReport()
        {
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string ProblemTitle { get; set; }
        public string CaseType { get; set; }
        public string Description { get; set; }
        public string Progress { get; set; }
        public System.DateTime ReportDate { get; set; }
        public Nullable<bool> isClosed { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public string Feedback { get; set; }
        public string Analysis { get; set; }
        public string FilePath { get; set; }
        public int UserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int LastUpdateUserID { get; set; }
    
        public virtual Admin_T Admin_T { get; set; }
        public virtual Admin_T Admin_T1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
