//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Appointments = new HashSet<Appointment>();
            this.ForgottenPasses = new HashSet<ForgottenPass>();
            this.Teachers = new HashSet<Teacher>();
            this.Inquiries = new HashSet<Inquiry>();
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string ImagePath { get; set; }
        public string FilePath { get; set; }
        public string Results { get; set; }
        public string Feedback { get; set; }
        public System.DateTime DoB { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> PassID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public Nullable<int> LiaisonID { get; set; }
        public int LastUpdateUserID { get; set; }
    
        public virtual Admin_T Admin_T { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual Assignment Assignment { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<ForgottenPass> ForgottenPasses { get; set; }
        public virtual ForgottenPass ForgottenPass { get; set; }
        public virtual LiaisonReport LiaisonReport { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<Inquiry> Inquiries { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
