//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ForgottenPasses = new HashSet<ForgottenPass>();
            this.LiaisonReports = new HashSet<LiaisonReport>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> LiaisonID { get; set; }
        public string UserRole { get; set; }
        public string Email { get; set; }
        public string isAdmin { get; set; }
    
        public virtual Admin_T Admin_T { get; set; }
        public virtual ICollection<ForgottenPass> ForgottenPasses { get; set; }
        public virtual ICollection<LiaisonReport> LiaisonReports { get; set; }
        public virtual LiaisonReport LiaisonReport { get; set; }
    }
}
